import type { LucideIcon } from 'lucide-react';

export interface ParkingType {
  id: string;
  name: string;
  icon: LucideIcon;
  basePrice: number;
}

export interface AddonService {
  id: string;
  name: string;
  price: number;
  icon: LucideIcon;
}

export interface Booking {
  id?: string; // Optional: will be generated by the database
  parkingType: string;
  entryDateTime: Date;
  exitDateTime: Date;
  addons: string[];
  discountCode?: string;
  driverName: string;
  phone: string;
  email: string;
  licensePlate: string;
  luggageCount?: number;
  passengerCount?: number;
  flightInfo?: string;
  total: number;
  status: 'Chờ xác nhận' | 'Xác nhận' | 'Đã vào bãi' | 'Đã rời bãi' | 'Đã hủy';
  createdAt?: Date;
}

export interface ParkingLot {
  id: string;
  name: string;
  type: 'Trong nhà' | 'Ngoài trời' | 'Khu vực dành cho người khuyết tật';
  capacity: number;
  basePrice: number;
  status: 'Hoạt động' | 'Bảo trì' | 'Đầy';
}
